In [1]:
%pip install requests beautifulsoup4

Requirement already satisfied: requests in c:\users\grega\appdata\roaming\python\python313\site-packages (2.32.5)
Requirement already satisfied: beautifulsoup4 in c:\users\grega\appdata\roaming\python\python313\site-packages (4.14.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\grega\appdata\roaming\python\python313\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\grega\appdata\roaming\python\python313\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\grega\appdata\roaming\python\python313\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\grega\appdata\roaming\python\python313\site-packages (from requests) (2025.10.5)
Requirement already satisfied: soupsieve>1.2 in c:\users\grega\appdata\roaming\python\python313\site-packages (from beautifulsoup4) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\grega\appdata\local\programs\python\python313\lib\site-packages (from beautifulsoup4) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
url_to_fetch = "https://www.goodreads.com/book/show/61851.Alcatraz_Versus_the_Evil_Librarians" # Example URL
response = requests.get(url_to_fetch)
html_content = response.text

In [3]:
soup = BeautifulSoup(html_content, 'html.parser')
book_data = [] # Run this cell before running the scraping loop

In [4]:
# Define the list of audience/age categories
audience_categories = ["Picture Book", "Childrens","Early Reader", "Middle Grade", "Young Adult", "New Adult", "Adult"]

In [8]:
urls = ["https://www.goodreads.com/book/show/623976.Alcatraz_Versus_the_Evil_Librarians"]

In [8]:
urls = [
    "https://www.goodreads.com/book/show/68427.Elantris",
"https://www.goodreads.com/book/show/1268479.Warbreaker",
"https://www.goodreads.com/book/show/28862254-white-sand-volume-1",
"https://www.goodreads.com/book/show/33551363-white-sand-volume-2",
"https://www.goodreads.com/book/show/39298848-white-sand-volume-3",
"https://www.goodreads.com/book/show/60696519-white-sand-omnibus",
"https://www.goodreads.com/book/show/28595941-arcanum-unbounded",
"https://www.goodreads.com/book/show/13578175-the-emperor-s-soul",
"https://www.goodreads.com/book/show/68428.Mistborn",
"https://www.goodreads.com/book/show/68429.The_Well_of_Ascension",
"https://www.goodreads.com/book/show/2767793-the-hero-of-ages",
"https://www.goodreads.com/book/show/28698036-secret-history",
"https://www.goodreads.com/book/show/10803121-the-alloy-of-law",
"https://www.goodreads.com/book/show/16065004-shadows-of-self",
"https://www.goodreads.com/book/show/18739426-the-bands-of-mourning",
"https://www.goodreads.com/book/show/23947089-the-lost-metal",
"https://www.goodreads.com/book/show/7235533-the-way-of-kings",
"https://www.goodreads.com/book/show/17332218-words-of-radiance",
"https://www.goodreads.com/book/show/34703445-edgedancer",
"https://www.goodreads.com/book/show/34002132-oathbringer",
"https://www.goodreads.com/book/show/54511226-dawnshard",
"https://www.goodreads.com/book/show/49021976-rhythm-of-war",
"https://www.goodreads.com/book/show/203578847-wind-and-truth",
"https://www.goodreads.com/book/show/17182126-steelheart",
"https://www.goodreads.com/book/show/18966322-mitosis",
"https://www.goodreads.com/book/show/15704459-firefight",
"https://www.goodreads.com/book/show/15704486-calamity",
"https://www.goodreads.com/book/show/58419574-lux",
"https://www.goodreads.com/book/show/13552643-defending-elysium",
"https://www.goodreads.com/book/show/36642458-skyward",
"https://www.goodreads.com/book/show/42769202-starsight",
"https://www.goodreads.com/book/show/57903876-sunreach",
"https://www.goodreads.com/book/show/57903879-redawn",
"https://www.goodreads.com/book/show/58465495-evershore",
"https://www.goodreads.com/book/show/57571215-cytonic",
"https://www.goodreads.com/book/show/43606308-defiant",
"https://www.goodreads.com/book/show/60531406-tress-of-the-emerald-sea",
"https://www.goodreads.com/book/show/60531410-the-frugal-wizard-s-handbook-for-surviving-medieval-england",
"https://www.goodreads.com/book/show/60531416-yumi-and-the-nightmare-painter",
"https://www.goodreads.com/book/show/60531420-the-sunlit-man",
"https://www.goodreads.com/book/show/210300489-isles-of-the-emberdark",
"https://www.goodreads.com/book/show/49798827-dark-one",
"https://www.goodreads.com/book/show/60373696-dark-one",
"https://www.goodreads.com/book/show/54615879-the-original",
"https://www.goodreads.com/book/show/623976.Alcatraz_Versus_the_Evil_Librarians",
"https://www.goodreads.com/book/show/3485562-alcatraz-versus-the-scrivener-s-bones",
"https://www.goodreads.com/book/show/6366110-alcatraz-versus-the-knights-of-crystallia",
"https://www.goodreads.com/book/show/7740659-alcatraz-versus-the-shattered-lens",
"https://www.goodreads.com/book/show/26114421-the-dark-talent",
"https://www.goodreads.com/book/show/59808314-bastille-vs-the-evil-librarians",
"https://www.goodreads.com/book/show/13452375-legion",
"https://www.goodreads.com/book/show/20886354-skin-deep",
"https://www.goodreads.com/book/show/37640636-lies-of-the-beholder",
"https://www.goodreads.com/book/show/39332065-legion",
"https://www.goodreads.com/book/show/8562526-firstborn",
"https://www.goodreads.com/book/show/25188109-perfect-state",
"https://www.goodreads.com/book/show/31176804-snapshot",
"https://www.goodreads.com/book/show/207974153-the-most-boring-book-ever"
]

In [9]:
for url in urls: # Use the urls list defined in cell b081e051
    response = requests.get(url)
    html_content = response.text
    soup = BeautifulSoup(html_content, 'html.parser')

    # Extract the book title
    title_h1 = soup.find('h1', {'data-testid': 'bookTitle'})
    title = title_h1.get_text(strip=True) if title_h1 else "Title not found"

    # Extract the book description
    description_div = soup.find('div', {'data-testid': 'description'})
    description = description_div.get_text(strip=True) if description_div else "Description not found"

    # Extract the published date
    published_date_p = soup.find('p', {'data-testid': 'publicationInfo'})
    published_date = published_date_p.get_text(strip=True) if published_date_p else "Published date not found"

    # Extract genre buttons and check against audience categories
    genres_in_audience = []
    non_audience_genres = []
    genre_buttons = soup.find_all('span', class_='BookPageMetadataSection__genreButton')
    for genre_button in genre_buttons:
        genre_span = genre_button.find('span', class_='Button__labelItem')
        if genre_span:
            genre = genre_span.get_text(strip=True)
            if genre in audience_categories:
                genres_in_audience.append(genre)
            else:
                non_audience_genres.append(genre)


    # Extract currently reading count
    currently_reading_div = soup.find('div', {'data-testid': 'currentlyReadingSignal'})
    currently_reading = currently_reading_div.get_text(strip=True).split()[0] if currently_reading_div else "Not found"

    # Extract want to read count
    to_read_div = soup.find('div', {'data-testid': 'toReadSignal'})
    to_read = to_read_div.get_text(strip=True).split()[0] if to_read_div else "Not found"

    # Extract average rating
    average_rating_div = soup.find('div', class_='RatingStatistics__rating')
    average_rating = average_rating_div.get_text(strip=True) if average_rating_div else "Not found"

    # Extract total ratings count
    ratings_count_span = soup.find('span', {'data-testid': 'ratingsCount'})
    ratings_count = ratings_count_span.get_text(strip=True).split()[0] if ratings_count_span else "Not found"

    # Extract total review count
    reviews_count_span = soup.find('span', {'data-testid': 'reviewsCount'})
    reviews_count = reviews_count_span.get_text(strip=True).split()[0] if reviews_count_span else "Not found"

    # Extract author name
    author_span = soup.find('span', {'data-testid': 'name'})
    author = author_span.get_text(strip=True) if author_span else "Not found"

    book_data.append({
        "URL": url,
        "Title": title,
        "Description": description,
        "Published Date": published_date,
        "Audience Genre": ", ".join(genres_in_audience) if genres_in_audience else "Not specified",
        "Non-Audience Genres": ", ".join(non_audience_genres) if non_audience_genres else "Not specified",
        "Currently Reading": currently_reading,
        "Want to Read": to_read,
        "Average Rating": average_rating,
        "Total Ratings": ratings_count,
        "Total Reviews": reviews_count,
        "Author": author

    })

In [10]:
book_df = pd.DataFrame(book_data)
book_df['Published Date'] = book_df['Published Date'].str.replace('First published ', '', regex=False)
book_df['Currently Reading'] = book_df['Currently Reading'].str.replace(',', '', regex=False).astype(int, errors='ignore')
book_df['Want to Read'] = book_df['Want to Read'].str.replace(',', '', regex=False).astype(int, errors='ignore')
book_df['Total Ratings'] = book_df['Total Ratings'].str.replace('ratings', '', regex=False).str.replace(',', '', regex=False).astype(int, errors='ignore')
book_df['Total Reviews'] = book_df['Total Reviews'].str.replace('reviews', '', regex=False).str.replace(',', '', regex=False).astype(int, errors='ignore')
book_df['Average Rating'] = book_df['Average Rating'].astype(float, errors='ignore')


# Reorder columns to include the new 'Non-Audience Genres' column after 'Total Reviews'
book_df = book_df[['Author', 'Title', 'Published Date', 'Audience Genre', 'Description', 'Average Rating', 'Total Ratings', 'Total Reviews', 'Non-Audience Genres', 'Currently Reading', 'Want to Read', 'URL']]

display(book_df)

,Author,Title,Published Date,Audience Genre,Description,Average Rating,Total Ratings,Total Reviews,Non-Audience Genres,Currently Reading,Want to Read,URL
0,Larry J. Siegel,Essentials of Criminal Justice [with InfoTrac],"October 1, 1997",Not specified,Master the ins and outs of the criminal justic...,3.72,74,0,"Textbooks, Crime, Reference, College",14,74,https://www.goodreads.com/book/show/61851.Alca...
1,Brandon Sanderson,Alcatraz Versus the Evil Librarians,"October 1, 2007","Young Adult, Middle Grade, Childrens",Alcatraz Versus the Evil Librariansis the firs...,3.92,35429,5172,"Fantasy, Fiction, Audiobook, Humor",1799,30572,https://www.goodreads.com/book/show/623976.Alc...

In [13]:
df = book_df.drop(0)
df

,Author,Title,Published Date,Audience Genre,Description,Average Rating,Total Ratings,Total Reviews,Non-Audience Genres,Currently Reading,Want to Read,URL
1,Brandon Sanderson,Alcatraz Versus the Evil Librarians,"October 1, 2007","Young Adult, Middle Grade, Childrens",Alcatraz Versus the Evil Librariansis the firs...,3.92,35429,5172,"Fantasy, Fiction, Audiobook, Humor",1799,30572,https://www.goodreads.com/book/show/623976.Alc...

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [14]:
df.to_csv('C:\Programming\Python\msba_capstone_dragonsteel\Goodreads Data\Alcatraz_vs_Evil_Librarians.csv', index=False)

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\grega\AppData\Local\Temp\ipykernel_27656\663596267.py:1: SyntaxWarning: invalid escape sequence '\P'
  df.to_csv('C:\Programming\Python\msba_capstone_dragonsteel\Goodreads Data\Alcatraz_vs_Evil_Librarians.csv', index=False)